/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChallengeFive;
import ChallengeFive.LinkedList.LinkedList;
public class App {
  public static void main(String[] args) {
    LinkedList();
    
  }
  public static void LinkedList(){
    LinkedList linkedList = new LinkedList();
    linkedList.insert("E");
    linkedList.insert("N");
    linkedList.insert("G");
    linkedList.insert("N");
    linkedList.insert("A");
    linkedList.insert("I");
    linkedList.insert("M.");
    System.out.println(linkedList);
    System.out.println(linkedList.include("N"));
    System.out.println(linkedList.include("P"));

  }
}
