/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChallengeFive;
import ChallengeFive.stucture.LinkedList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {

    @Test
    public void isEmptyTest() {
      LinkedList testList = new LinkedList();


    }

    @Test
    public void addNewNodeAtEndTest() {
      LinkedList testList = new LinkedList();
      testList.insert("M");
      testList.insert("M");

    }


    @Test
    public void addBeforeAndAfterTest() {
      LinkedList testList = new LinkedList();
      testList.insert("N");
      testList.insert("A");
      testList.insert("I");
      testList.insert("M");
      assertEquals(" { N }  ->  { A }  ->  { I }  ->  { M }  ->  NULL ",testList.toString());

    }
  }

