/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChallengeFive;
import org.junit.jupiter.api.Test;

class AppTest {
  //    @Test void appHasAGreeting() {
//        LinkedList classUnderTest = new LinkedList();
//    assertEquals();
//    }
//    @Test void appHasAGreeting() {
//        LinkedList classUnderTest = new LinkedList();
//    assertEquals();
//    }
    @Test void appHasAGreeting(){
      assertTrue(appHasAGreeting(), "NA");
    }
}
